In [ ]:
# problem -1 

import pandas as pd;

df = pd.read_csv("IRIS.csv")

In [15]:
# A - displaying info

df.head(10) #first 10 rows 
print(df.shape , df.dtypes) #shape and data
df.describe().loc[["mean" ,"std" ,"min","max"]]

(150, 5) sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

      sepal_length  sepal_width  petal_length  petal_width
mean      5.843333     3.054000      3.758667     1.198667
std       0.828066     0.433594      1.764420     0.763161
min       4.300000     2.000000      1.000000     0.100000
max       7.900000     4.400000      6.900000     2.500000

In [ ]:
# B -  Select particular rows with the condition

df.loc[(df['petal_length'] <= 4.5) & (df['species'] == 'Iris-virginica')]

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []